apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: test-demo
    app.kubernetes.io/instance: test-demo-instance
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: backend
    app.kubernetes.io/managed-by: kubectl
  name: test-demo
  namespace: sample-eks-ns
spec:
  selector:
    app: test-demo
  type: LoadBalancer
  ports:
   -  protocol: TCP
      port: 80
      targetPort: 3000
